AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: perplexity-clone

Parameters:
  Serpapikey:
    Type: String
    Description: serp api key
    Default: e64bd8a7afb21c6b20d25bef72e920f3e5c729e6a6cb1f15dbfb9e2b4d996ff9

# GLOBAL VARIABLES
Globals:
  Function:
    Runtime: python3.11
    Architectures:
      - x86_64
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  # Main LAMBDA
  MainLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Timeout: 15
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          SERP_API_KEY: !Ref Serpapikey
    Metadata:
      BuildMethod: python3.11


Outputs:
  MyFunctionUrlEndpoint:
    Description: "My Lambda Function URL Endpoint"
    Value: !GetAtt MainLambdaUrl.FunctionUrl